---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ORG_DOMAIN}}
  name: create-configtx
spec:
  template:
    metadata:
      labels:
        app: create-configtx
        tier: {{ORG_DOMAIN}}
    spec:
      restartPolicy: "Never"
      containers:
      - name: create-configtx
        image: alpine:3.12.0
        command: ["sh"]
        # args:  ["-c", "ls -al /scripts/;"]
        args:  ["-c", "apk add bash; ./scripts/gen-configtx.sh 2>&1;"]
        volumeMounts:
          - name: nfs
            mountPath: /scripts
            subPath: {{EFS_EXTEND}}/akc-ca-scripts
          - name: nfs
            mountPath: /data/
            subPath: {{EFS_EXTEND}}/akc-ca-data
      volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}
