---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{DOMAIN}}
  name: explorerpod
spec:
  serviceName: explorer
  replicas: 1
  selector:
    matchLabels:
      app: explorer
      tier: {{DOMAIN}}
  template:
    metadata:
      labels:
        app: explorer
        tier: {{DOMAIN}}
    spec:
      containers:
      - name: explorer
        image: akachain/devtool-explorer
        env:
          - name: DATABASE_HOST
            value: explorer-db.{{DOMAIN}}
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USERNAME
            value: postgres
          - name: DATABASE_PASSWD
            value: {{DATABASE_PASSWORD}}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
          - name: nfs
            mountPath: /opt/explorer/crypto-config/
            subPath: {{EFS_EXTEND}}/akc-ca-data/crypto-config
          - name: nfs
            mountPath: /opt/explorer/app/platform/fabric/config/
            subPath: {{EFS_EXTEND}}/explorer-config
          - name: nfs
            mountPath: /tmp/crypto-store/
            subPath: {{EFS_EXTEND}}/admin/crypto-store
          - name: nfs
            mountPath: /opt/explorer/crypto-path/
            subPath: {{EFS_EXTEND}}/admin/crypto-path
      volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}
