apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{REG_DOMAIN}}
  name: register-org-{{ORG}}
spec:
  template:
    metadata:
      labels:
       app: hyperledger
       role: peer
       org: {{REG_DOMAIN}}
       name: register-org-{{ORG}}
    spec:
     restartPolicy: "Never"
     containers:
       - name: register-org-{{ORG}}
         image: hyperledger/fabric-ca:{{FABRIC_CA_TAG}}
         env:
          - name: ORG
            value: {{ORG}}
         command: ["sh"]
         args:  ["-c", "/scripts/register-org.sh 2>&1;"]
         volumeMounts:
          - mountPath: /scripts
            name: nfs
            subPath: {{EFS_EXTEND}}/akc-ca-scripts
          - mountPath: /data
            name: nfs
            subPath: {{EFS_EXTEND}}/akc-ca-data
     volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}