---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ORDERER_DOMAIN}}
  name: generate-artifacts
spec:
  template:
    metadata:
      labels:
        app: generate-artifacts
        tier: {{ORDERER_DOMAIN}}
    spec:
      restartPolicy: "Never"
      containers:
      - name: generate-artifacts
        image: alpine:3.12.0
        command: ["sh"]
        # args:  ["-c", "ls -al /scripts/;"]
        args:  ["-c", "apk add bash; ./scripts/gen-network-config.sh 2>&1;"]
        volumeMounts:
          - name: nfs
            mountPath: /scripts
            subPath: {{EFS_EXTEND}}/akc-ca-scripts
          - name: nfs
            mountPath: /data/app/artifacts/
            subPath: {{EFS_EXTEND}}/admin-v2/artifacts
      volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}
      
