---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ORDERER_DOMAIN}}
  name: admin-v1
spec:
  serviceName: admin-v1
  replicas: 1
  selector:
    matchLabels:
      app: admin-v1
      tier: {{ORDERER_DOMAIN}}
  template:
    metadata:
      labels:
        app: admin-v1
        tier: {{ORDERER_DOMAIN}}
    spec:
      containers:
      - name: admin-v1
        image: docker.pkg.github.com/akachain/akc-admin/master:v1.5.2
        ports:  
        - containerPort: 4001
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        volumeMounts:
          - name: nfs
            mountPath: /shared/
            subPath: {{EFS_EXTEND}}/akc-ca-data
          - name: nfs
            mountPath: /tmp/crypto-store/
            subPath: {{EFS_EXTEND}}/admin/crypto-store
          - name: nfs
            mountPath: /data/app/crypto-path/
            subPath: {{EFS_EXTEND}}/admin/crypto-path
          - name: nfs
            mountPath: /data/app/artifacts/
            subPath: {{EFS_EXTEND}}/admin-v2/artifacts
      volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}
      imagePullSecrets:
      - name: mamba