apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ORG_DOMAIN}}
  name: generate-ccp-{{ORG_NAME}}
spec:
  template:
    metadata:
      labels:
       app: hyperledger
       role: peer
       org: {{ORG_NAME}}
       name: generate-ccp-{{ORG_NAME}}
    spec:
     restartPolicy: "Never"
     containers:
       - name: generate-ccp-{{ORG_NAME}}
         image: alpine:3.12.0
         env:
          - name: ORG
            value: {{ORG_NAME}}
         command: ["sh"]
         args:  ["-c", "apk add bash; ./scripts/generate-ccp.sh 2>&1;"]
         volumeMounts:
          - mountPath: /scripts
            name: nfs
            subPath: {{EFS_EXTEND}}/akc-ca-scripts
          - mountPath: /data
            name: nfs
            subPath: {{EFS_EXTEND}}/akc-ca-data
          - mountPath: /shared/admin-v2/artifacts
            name: nfs
            subPath: {{EFS_EXTEND}}/admin-v2/artifacts
     volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}