---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{DOMAIN}}
  name: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      role: prometheus
      type: stateful
  template:
    metadata:
      labels:
        app: hyperledger
        role: prometheus
        type: stateful
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        # resources:
        #   requests:
        #     memory: "150Mi"
        #     cpu: "350m"
        #   limits:
        #     memory: "3000Mi"
        #     cpu: "2"
        command: ["sh", "-c", "prometheus --config.file=/etc/prometheus.yml"]
        ports:
        - containerPort: 9090

        volumeMounts:
          - name: nfs
            mountPath: /etc/
            subPath: {{EFS_PATH}}/{{EFS_EXTEND}}/promconfig
      volumes:
      - name: nfs
        persistentVolumeClaim: 
          claimName: {{CLAIM_NAME}}
